### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childNodes' of null

### ISSUE THREAD

**Issue by davidbuhler** [ProminentEdge/mil-2525c-generator#3]
I receive the following error when making a request:

**Actual Behavior**
Javascript console shows an error
> content.js:218: Uncaught TypeError: Cannot read property 'childNodes' of null
Request:
http://localhost:3000/symbol/get/iaaxscc-----

**Expected Behavior**
Javascript console shows no error

**Comment by garnertb** [comment]
See comment on https://github.com/ProminentEdge/mil-2525c-generator/issues/4.  Closing since this is likely due to Chrome extensions.
