### ISSUE TITLE
global-shortcut.js:9 Uncaught TypeError: Cannot read property 'hasAttribute' of null

### ISSUE THREAD

**Issue by davidbuhler** [ProminentEdge/mil-2525c-generator#4]
I receive the following error when making a request:

**Actual Behavior**
Javascript console shows an error
global-shortcut.js:9 Uncaught TypeError: Cannot read property 'hasAttribute' of null
Request:
http://localhost:3000/symbol/get/iaaxscc-----

**Expected Behavior**
Javascript console shows no error

**Comment by garnertb** [comment]
Are you using chrome?  Client-side errors are most likely coming from an extension since this service does not load any client-side JS dependencies.  You can open the url in FF to confirm.
