### ISSUE TITLE
http://localhost:3000/favicon.ico 500 (Internal Server Error)

### ISSUE THREAD

**Issue by davidbuhler** [ProminentEdge/mil-2525c-generator#5]
I receive the following error when making a request:

**Actual Behavior**
Javascript console shows an error
GET http://localhost:3000/favicon.ico 500 (Internal Server Error)
Request:
http://localhost:3000/symbol/get/iaaxscc-----

**Expected Behavior**
Javascript console shows no error

**Comment by garnertb** [comment]
I cannot reproduce this:
```
$ node --version
v0.10.33
$ ./www 
milsymbol.js v0.5.2b - Copyright (c) 2015 Måns Beckman  http://www.spatialillusions.com
mil-2525c-generator running.
GET /symbol/get/iaaxscc----- 200 1.117 ms - -
GET /favicon.ico 404 213.927 ms - 1266
```

**Comment by garnertb** [comment]
Closing this.  @davidbuhler please re-open if you can reproduce.
